### ISSUE TITLE
Did CC Costa Rica received the wire?

### ISSUE THREAD

**Issue by claudiorrrr** [creativecommons/cclatam-mini-grants#4]
Hi Scott, just wanted to know whether CC Costa Rica did received the wire related with their minigrants project. The contact person there is Meilyn Garro.

**Comment by Scott-CC** [comment]
The one that I saw was submitted at the end of January, for 1,000 to Ana Evelyn Del Pinal, that went out on January 29th.  I know there were going to be a couple of others, but I don't recall getting anything else.

**Comment by claudiorrrr** [comment]
Yeah, but that was for the other project submitted. I will send you an email with the detailed info ;)
